---
title: "Does Safegraph correlate with COVID19 cases?"
author: "Sahir, Peter, Sahar"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    self_contained: true
    thumbnails: false
    lightbox: true
    gallery: false
    highlight: tango
editor_options: 
  chunk_output_type: console
---

```{r setup, echo=FALSE, message=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.width = 13, fig.height = 13)
options(tidyverse.quiet = TRUE)
```



```{r}
library(targets)
library(here)

# September 10 model with ccvi quintile, log(population) offset, density fixed effect. FINAL MODEL USED IN PAPER
# gam_result <- readRDS(file = here::here("results/five_states_start_open_4_14_lags_CCVI_NYT_predifnedKnots_ns_k5_m2_ccvi_quintile.rds"))

# September 10 model with log(population) offset, density fixed effect
#gam_result <- readRDS(file = here::here("results/five_states_start_open_4_14_lags_CCVI_NYT_predifnedKnots_ns_k5_m2.rds"))

gam_result <- tar_read(gam_res)

index <- which(sapply(gam_result, function(i) !is.null(attr(i$GAM,"class"))))
state <- sapply(index, function(i) unique(gam_result[[i]][["DTfinal"]][["state"]]))
outcome_type <- sapply(index, function(i) unique(gam_result[[i]][["DTfinal"]][["outcome_type"]]))
metric_type <- sapply(index, function(i) unique(gam_result[[i]][["DTfinal"]][["metric_type"]]))

```



```{r, echo=FALSE, results='asis'}

src <- mapply(knitr::knit_expand,
              file = here::here("fpca_single_template.Rmd"),
              index = index,
              state = state,
              outcome_type = outcome_type,
              metric_type = metric_type)


# src <- mapply(knitr::knit_expand, 
#               file = here::here("report/fpca_single_template.Rmd"),
#               state = c("Ohio","North Carolina","Florida"),
#               rdataname = c("results/OH_gam_FPCA_devicenothome_nytcases_4_14_lag.RData",
#                             "results/NC_gam_FPCA_devicenothome_nytcases_4_14_lag.RData",
#                             "results/FL_gam_FPCA_devicenothome_nytcases_4_14_lag.RData"))

res = knitr::knit_child(text = unlist(src), quiet = TRUE)
cat(res, sep = '\n')
```




# Likelihood Ratio Tests

A lower `Resid. Dev` indicates a better fit. The first row of each table is for single Metric, the second row is for PCA. 

```{r, results='asis'}
lapply(seq(1,7,by=2), function(i) {
  # print(unique(gam_res[[i]]$DTfinal$state))
  cap <- sprintf("Comparison of single Metric vs. PCA for %s",unique(gam_result[[i]]$DTfinal$state))
  knitr::kable(anova(gam_result[[i+1]]$GAM, gam_result[[i]]$GAM, test = "Chisq", freq = TRUE),
               caption = cap)
}
  )


```




```{r}
knitr::knit_exit()
```